# Generated by Django 5.0.6 on 2024-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('id_publicacion', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
